# Generated by Django 5.2.4 on 2025-07-19 12:57

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=50, validators=[api.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[api.validators.validate_name],
            ),
        ),
    ]
