# Generated by Django 5.2.4 on 2025-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="target_class",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
