# Generated by Django 5.2.4 on 2025-07-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_options_exam_examsubmission_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.AlterField(
            model_name='exam',
            name='assigned_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='examsubmission',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='one_submission_per_exam'),
        ),
    ]
