# Generated by Django 5.2.4 on 2025-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_exam_target_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="target_standard",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
